# Generated by Django 4.2.2 on 2023-06-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="code",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
