# Generated by Django 4.2.2 on 2023-06-19 18:22
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_order_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="frequently_bought_together",
            field=models.ManyToManyField(
                related_name="freq_bought_together", to="api.product"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="similar_products",
            field=models.ManyToManyField(
                related_name="similar_products", to="api.product"
            ),
        ),
    ]
